server.port=${PORT:4310}
spring.application.name=skyfare-audit-service
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/skyfare}
spring.data.mongodb.database=${MONGODB_DB_NAME:skyfare}
